# GENERAL
title: wikiIPA
email: nquinones@g.harvard.edu
description: >-
  Lorem ipsum

# JEKYLL STUFF
#remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"
color_scheme: nqo
logo: "/assets/images/logo.png"

# SITE SEARCH
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false